### ISSUE TITLE
Load default view folder from modules.

### ISSUE THREAD

**Issue by gemblue** [panada/Panada#71]
Hallo mas.

Ketika menerapkan hmvc ada kasus kita tetap mau load view dr default folder. Gak dari folder view di module. Tujuan modular hanya untuk memanage library, model, controller terkait module tersebut saja.. untuk view sendiri bisa jadi terpusat bersama dengan file view lain.

Untuk project saya dr dulu ada opsi kaya gini juga sih. 

Kalau memang berguna mungkin nnt saya mau tambahin di panada controller. Tapi belum tau user lain ada kasus kaya gini juga gak.

**Comment by ikandars** [comment]
Boleh bgt mas. Beberapa kali saya dan teman mengalami kondisi ini. Selama ini akhirnya kita membuat semacam controller helper yg digunakan untuk memanggil controller utama. Tapi kalau ini bisa diotomatisasi saya rasa akan lebih bagus.

thx
