### ISSUE TITLE
Routing Feature

### ISSUE THREAD

**Issue by ikandars** [panada/Panada#75]
Panada 2.0 will have routing feature

**Comment by rizqyhi** [comment]
+1

**Comment by gemblue** [comment]
Yeah

**Comment by gravitano** [comment]
[Saran]

Mungkin untuk fitur ini bisa pake [FastRoute](https://github.com/nikic/FastRoute) atau [Route](http://route.thephpleague.com/) dari @thephpleaue.

**Comment by ikandars** [comment]
Tadinya kita sempet mempertimbangkan untuk menggunakan [Puk](http://c9s.github.io/Pux/) tapi akhirnya kita memutuskan untuk membuat sendiri yang sourcenya bisa di cek di branch [router4panada-2.x](https://github.com/panada/Panada/tree/router4panada-2.x) yang dikoordinir oleh @fudanchii

**Comment by anisku11** [comment]
Semoga v. 2.0 Cepet dirilis
