### ISSUE TITLE
Encription.php reported as malware 

### ISSUE THREAD

**Issue by tyaslab** [panada/Panada#88]
When I host panada to a shared host, Encription.php was detected as malware. It caused my hosting account  suspended.

```
HOST:      xxx.xxx.net
SCAN ID:   151021-0332.525815
STARTED:   Oct 21 2015 03:32:59 +0700
COMPLETED: Oct 21 2015 03:35:24 +0700
ELAPSED:   145s [find: 20s]

PATH:          /home*/*/public_html/ /var/www/html/ /usr/local/apache/htdocs/
RANGE:         1 days
TOTAL FILES:   61587
TOTAL HITS:    1
TOTAL CLEANED: 0

SUSPENDED ACCOUNTS:
xxx

FILE HIT LIST:
{HEX}php.base64.v23au.185  :  /home/xxx/public_html/xxx/panada/Resources/Encryption.php  =>  /usr/local/maldetect/quarantine/Encryption.php.187503914
===============================================
Linux Malware Detect v1.5 < proj@rfxn.com >
```

**Comment by ikandars** [comment]
If you didn't use this library at any your controller or didn't use cookie base session with encryption enabled, you can remove this file.
And thanks for your report. We will change the way encryption handling on this class. 
On Oct 21, 2015 5:01 AM, Yusuf Ali <notifications@github.com> wrote:When I host panada to a shared host, Encription.php was detected as malware. It caused my hosting account  suspended.

HOST:      xxx.xxx.net
SCAN ID:   151021-0332.525815
STARTED:   Oct 21 2015 03:32:59 +0700
COMPLETED: Oct 21 2015 03:35:24 +0700
ELAPSED:   145s [find: 20s]

PATH:          /home*/*/public_html/ /var/www/html/ /usr/local/apache/htdocs/
RANGE:         1 days
TOTAL FILES:   61587
TOTAL HITS:    1
TOTAL CLEANED: 0

SUSPENDED ACCOUNTS:
xxx

FILE HIT LIST:
{HEX}php.base64.v23au.185  :  /home/xxx/public_html/xxx/panada/Resources/Encryption.php  =>  /usr/local/maldetect/quarantine/Encryption.php.187503914
===============================================
Linux Malware Detect v1.5 < proj@rfxn.com >
